name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Add NuGet to PATH
      uses: nuget/setup-nuget@v1
  
    - name: Install dependencies
      run: nuget install Grasshopper -OutputDirectory ./lib/GH -source https://api.nuget.org/v3/index.json
      
    - name: Download dependency lib. LibIGL, Eigen
      run: |
        git clone https://github.com/libigl/libigl.git ./external/libigl
        git clone https://gitlab.com/libeigen/eigen.git ./external/eigen

 
    - name: Build
      run: msbuild /p:IncludePath="external/eigen;external/libigl/include"

